1. 错误时机，全局错误，异步错误，渲染错误
2. 捕获异常的方法、发送相关埋点到监控平台
3. 业界做法：如sentry.js

## window.onerror

全局监听异常（**vue 场景下不会触发**，有专门的异常捕获方法，详见下文）

当 js 运行错误时，window 会触发一个 ErrorEvent 接口的 error 事件，并执行 window.onerror。既此，可以用来自动收集错误报告。

**语法**

```js
window.onerror = function(message,source,lineno,colno,error){ ... }
```

参数说明：

- `message`：错误信息（字符串）。可用于HTML `onerror=""`处理程序中的`event`。
- `source`：发生错误的脚本URL（字符串）
- `lineno`：发生错误的行号（数字）
- `colno`：发生错误的列号（数字）
- `error`：Error 对象

返回值：若**返回false，则浏览器会正常报错**。则若该函数**返回true，则阻止执行默认事件处理函数**，也就是不会在控制台打印错误。

eg：

```html
<html>
  <head>
    <script type="text/javascript">
      onerror = handleErr;
      var txt = "";
      function handleErr(msg, source, lineno, colno, error) {
        txt = "There was an error on this page.\n\n";
        txt += "错误信息: " + msg + "\n";
        txt += "发生错误的脚本URL: " + source + "\n";
        txt += "发生错误的行数: " + lineno + "\n\n";
        txt += "发生错误的列数: " + colno + "\n\n";
        txt += "Click OK to continue.\n\n";
        alert(txt);
        return false;
      }
      function message() {
        adddlert("Welcome guest!");
      }
    </script>
  </head>

  <body>
    <input type="button" value="View message" onclick="message()" />
  </body>
</html>
```

点击 View message 的时候，就会显示如下弹窗：

![弹框](https://i.loli.net/2020/03/24/v16RMg4BHjK3Srh.png)

![](https://i.loli.net/2020/03/24/KOnJsIG7tX3HpwZ.png)

## try...catch

可以利用catch捕获try代码块中抛出的异常，同时可以在catch中发送相关埋点到监控平台。但**无法捕获到try代码块中的异步任务抛出的异常**（eventloop 相关，执行上下文改变）。

## 异步的错误捕获

如何捕获异步函数比如promise的异常：

```js
// 使用reject
const p1 = new Promise((reslove, reject) => {
  if(1) {
    reject();
  }
});

// Promise 不管内部是 reject 还是 throw new Error，都可以通过 catch 捕获
p1.catch((e) => console.log('p1 error'));
const p1 = new Promise((resolve,reject)=>{
  throw new Error(123)
}).catch(e =>{
  console.log(e.message)
})

// 或者then里面的错误捕获
const p2 = Promise.resolve().then(()=>{
  try{
    throw new Error(123)
  } catch(e) {
    return e;
  }
}).then(e => console.log(e.message))
```

举一反三，如何使用 async/await 捕获错误：

```js
function promise(){
  return new Promise((resolve,reject)=>{
    setTimeout(()=>{reject('failue...')},100)
  })
}

async function main(){
  try{
    const res = await promise(); // 被catch捕获
    console.log(res,'res')
  } catch(err){
    console.log(err,'e.message')
  }
}

main();
```

async 函数以同步的形式执行异步代码，其实本质上也是一个promise链，对于异常捕获方面，关键在于其生成器也有的“throw”状态，当 await 内部 promise 状态reject 后，就会向上冒泡，直到 step("throw") 执行，然后 catch 里的代码 `console.log(e, 'e.message')`

## 关于 Vue 异常捕获

 Vue 自身已经通过 try...catch... 处理，而不会触发 window.onerror 事件，而我们有时候也需要专门对 Vue 进行异常捕获，这时可以使用 [Vue.config.errorHandler](https://links.jianshu.com/go?to=https%3A%2F%2Fcn.vuejs.org%2Fv2%2Fapi%2F%23errorHandler) 对 Vue 进行**全局的异常捕获**。

指定组件的渲染和观察期间未捕获错误的处理函数。这个处理函数被调用时，可获取错误信息和 Vue 实例。在处理函数中，我们除了发送相关的埋点信息，可以在控制台打印一下相关的报错信息，注意默认这个捕获的方法是**不会自动在控制台打印**的，这对于我们开发来讲是不友好的

```jsx
Vue.config.errorHandler = function (err, vm, info) {
  // handle error
  // `info` 是 Vue 特定的错误信息，比如错误所在的生命周期钩子
  // 只在 2.2.0+ 可用
}
```

## 生产环境下的异常捕获

当我们使用webpack 打包压缩后，生成的代码是混淆的，这主要出于安全和性能两个方面考虑。
但是在这样也同时不利于定位和调试问题，所以可以开启 source map 模式。我们只需要配置 webpack 的 devtool 选项即可，详见[webpack devtool 官网](https://links.jianshu.com/go?to=https%3A%2F%2Fwebpack.js.org%2Fconfiguration%2Fdevtool%2F)。示例所示:

```bash
devtool: 'eval-source-map'
```

source map 虽然很好用，但是出于安全考虑（如果在生产模式使用source-map，很容易造成源码泄露等安全风险），了解到有一种技巧：

首先本地依然生成 source map 文件，但是我们不上传服务器，只保留在本地服务器，当报错时使用 whistle 拦截和线上的js替换成本地的 source map 文件，就相当于加载本地的 source map 文件了。

## 业界用到的一些方案

如

使用 sentry.js(https://sentry.io/welcome/) 

[]: https://sentry.io/welcome/	"sentry.js"

 或 bad.js：





